# Generated by Django 4.2.7 on 2026-01-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('web', 'Web Form'), ('chatbot', 'Chatbot'), ('email', 'Email')], default='web', max_length=20),
        ),
    ]
