# Generated by Django 6.0.1 on 2026-03-06 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='customer_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.company'),
        ),
    ]
