# Generated by Django 6.0.1 on 2026-03-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_customer_company_ticket_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('support', 'Support'), ('operations', 'Operations')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('editor', 'Editor'), ('employee', 'Employee')], max_length=20),
        ),
    ]
