# Generated by Django 6.0.1 on 2026-03-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_ticket_assigned_to_ticket_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
