# Generated by Django 4.2.7 on 2026-03-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_company_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('editor', 'Editor'), ('hybrid', 'Hybrid'), ('employee', 'Employee')], max_length=20),
        ),
    ]
