# Generated by Django 4.2.7 on 2026-03-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registration_source',
            field=models.CharField(choices=[('internal', 'Internal'), ('self', 'Self-Registered')], default='internal', max_length=20),
        ),
    ]
