# Generated by Django 4.2.7 on 2026-03-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_company_registration_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='registration_source',
        ),
        migrations.AddField(
            model_name='company',
            name='registration_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('self_registered', 'Self Registered')], default='internal', max_length=20),
        ),
    ]
