# Generated by Django 5.0 on 2026-03-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_remove_company_registration_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gmail_app_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='gmail_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_instance_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
