# Generated by Django 6.0.3 on 2026-03-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_company_gmail_app_password_company_gmail_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('running', 'Running'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('complete', 'Complete'), ('closer', 'Closer'), ('invoice', 'Invoice'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='inquiry', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('running', 'Running'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('inquiry', 'Inquiry'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closer', 'Closer'), ('invoice', 'Invoice'), ('closed', 'Closed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
