# Generated by Django 6.0.3 on 2026-03-20 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_department_userprofile_department_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='department_obj',
            new_name='department',
        ),
    ]
